[package]
name = "numas-wasm"
version = "0.2.2"
authors = ["Lukáš Zahradník <lukaszahradnik96@seznam.cz>"]
edition = "2018"

[dependencies]
numas = "0.2.5"

[build]
target="wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib"]
path = "output/lib.rs"

[profile.release]
opt-level = 3
lto = true