[package]
name = "numas-wasm"
version = "0.1.0"
authors = ["Lukáš Zahradník <lukaszahradnik96@seznam.cz>"]
edition = "2018"

[dependencies]

[build]
target="wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib"]
path = "output/main.rs"

[profile.release]
lto = true